### ISSUE TITLE
Files explicitly given in the command line not being deduplicated

### ISSUE THREAD

**Issue by LewisGaul** [nicoddemus/pytest-drop-dup-tests#5] opened 2020-05-22 12:23 UTC
This is simply not working for me. Any ideas why/what to try?
```
$PYTHONPATH=svr pytest test/ test/run_test.py -v
======================================================== test session starts =========================================================
platform linux -- Python 3.6.8, pytest-5.4.2, py-1.8.1, pluggy-0.13.1 -- /mnt/c/Users/legaul/ET/helper-scripts/src/tools-listing/test/.venv/bin/python3
cachedir: .pytest_cache
rootdir: /mnt/c/Users/legaul/ET/helper-scripts/src/tools-listing/test, inifile: pytest.ini
plugins: drop-dup-tests-0.2.0
collected 3 items

test/run_test.py::LoadYamlTest::test_success PASSED                                                                            [ 33%]
test/yaml_test.py::test_yaml PASSED                                                                                            [ 66%]
test/run_test.py::LoadYamlTest::test_success PASSED                                                                            [ 66%]

========================================================= 3 passed in 0.67s ==========================================================

**Comment by nicoddemus** [comment] 2020-05-22 13:14
Hi @LewisGaul,

Hmmm if you pass a test file explicitly on the command line (`test/run_test.py`), pytest never gets plugins a chance to ignore it.

When evaluating the `test/` argument, we collect `test/run_test.py` and store that in a set, to ignore it the next time it appears as a collection option. Problem is when evaluating `test/run_test.py`, pytest never calls the `pytest_ignore_collect` hook by design.

The original use case for the plugin was to ignore duplicated tests when given multiple directories, not explicit test modules. For example, if you pass `test/` twice, you will see the tests will be executed only once each, instead twice each in plain pytest.

Hope this helps!

**Comment by LewisGaul** [comment] 2020-05-22 20:27
Ahh that explains it. Is there nothing that can be done here then?

When doing a web search on this issue I came across one instance where this plugin's behaviour was desirable for the purpose of specifying a set of tests to run first, e.g.
`pytest test/run_first/ test/`
This still seems like a valid thing to want to do by specifying a test file as opposed to a directory.

In my case, I have a bash wrapper that by default should run all tests, but also passes all arguments through to pytest:
`PYTHONPATH=svr pytest test/ $@`
I want to be able to pass individual test files in without the tests being run twice. I thought that just running 'pytest' should automatically discover the tests, but it takes ages/hangs (possibly because it's searching the whole tree for test files?), which is why I've added the 'test/' arg. Any thoughts here?

**Comment by LewisGaul** [comment] 2020-05-22 21:03
So I've realised I can use a `pytest.ini` file to specify `testpaths = test`, but this still isn't ideal because it seems the configuration file has to be in the directory pytest is being run from (or possibly higher up), which isn't a viable option for me.

I tried passing this option in on the CLI with `-o testpaths=test` but this didn't seem to do anything (I guess pytest is still looking for a config file?).

I also thought passing `--rootdir test` might work, but this didn't seem to do anything either :(

**Comment by LewisGaul** [comment] 2020-05-22 21:22
Sorry for the multiple comments - I've found a solution, although it feels a bit ugly so I'd welcome an alternative suggestion! (Why is a pytest.ini file required just to be able to specify options on the CLI? Why is the 'testpaths' path arg relative to cwd instead of the pytest.ini file itself?)

- `pytest.ini` file under `test/` (can be empty)
- In the bash wrapper (can be run from anywhere, although it displays the full relative path to the tests):
`PYTHONPATH="$THISDIR/svr" pytest -c "$THISDIR/test/pytest.ini" -o "testpaths=$THISDIR/test" $@`

**Comment by nicoddemus** [comment] 2020-05-23 11:58
> Sorry for the multiple comments

No worries!

> Why is a pytest.ini file required just to be able to specify options on the CLI? Why is the 'testpaths' path arg relative to cwd instead of the pytest.ini file itself?

Not sure actually, this should have worked.

Passing `pytest test/` should work fine if we change the plugin to also discard duplicated test files... should be possible, let me take a stab at it.

**Comment by nicoddemus** [comment] 2020-05-23 12:32
`0.3.0` released with this feature, let me know if it works now! 👍

**Closed as completed** 2020-05-23 12:32 UTC
Labels: question

**Comment by nicoddemus** [comment] 2020-05-23 12:37
Btw if you are interested, here's the code which drops duplicated tests:

https://github.com/nicoddemus/pytest-drop-dup-tests/blob/94c82108677a12b19c9f7bc0076fb0301147be6a/pytest_drop_dup_tests.py#L14-L26

**Comment by LewisGaul** [comment] 2020-05-23 13:02
Thanks for the fix! This does work, although has the unfortunate side effect of display a number of 'deselected' tests. I'm not really sure why it wouldn't make most sense for Pytest itself to ignore duplicate tests... But appreciate you making this enhancement so quickly :)

**Comment by nicoddemus** [comment] 2020-05-23 13:07
The reasons were discussed in https://github.com/pytest-dev/pytest/issues/1187 if you are interested.

Thanks again for the report. 👍
