### ISSUE TITLE
Incompatible with pytest 8.1.0

### ISSUE THREAD

**Issue by marcodicro-dp** [nicoddemus/pytest-drop-dup-tests#7] opened 2024-03-04 19:32 UTC
Hi!

I'm using this plugin and I had errors today because pytest included breaking changes in v8.1.0: https://docs.pytest.org/en/latest/changelog.html

I wanted to know if this plugin is still needed to remove duplicate tests or this has finally been turned into the default  pytest behavior. Because if so I'd love to remove the dependency, and maybe this should be made clear in this repo's readme.

Thank you very much!

**Comment by nicoddemus** [comment] 2024-03-04 20:13
Hi,

It is still needed, pytest's behavior has not changed (as discussed, it will run tests multiple times by design if they are passed multiple times in the command-line).

I will work on a fix.

**Comment by nicoddemus** [comment] 2024-03-04 21:00
Fixed by https://github.com/nicoddemus/pytest-drop-dup-tests/pull/8, 1.0.0 is out. 👍

**Closed as completed by nicoddemus** 2024-03-04 21:00 UTC

**Comment by marcodicro-dp** [comment] 2024-03-04 21:12
Thanks!!! @nicoddemus
